# services:
#   web:
#     build: requirements/composetest/
#     ports:
#       - "8000:5000"
#     develop:
#       watch:
#         - action: sync
#           path: requirements/composetest/
#           target: /code
#   redis:
#     image: "redis:alpine"

services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
     - .env
    networks:
      - wp-site
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    # init: true
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - wp-site
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - www-data:/var/www/html/

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - wp-site
    volumes:
      - www-data:/var/www/html
    depends_on:
      - mariadb

networks:
  wp-site:
    driver: bridge

volumes:
  www-data:
    driver_opts:
      type: local
      device: ${HOME}/data/www-data
      o: bind
  db-data:
    driver_opts:
      type: none
      device: ${HOME}/data/db-data
      o: bind