# services:
#   web:
#     build: requirements/composetest/
#     ports:
#       - "8000:5000"
#     develop:
#       watch:
#         - action: sync
#           path: requirements/composetest/
#           target: /code
#   redis:
#     image: "redis:alpine"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"