# services:
#   web:
#     build: requirements/composetest/
#     ports:
#       - "8000:5000"
#     develop:
#       watch:
#         - action: sync
#           path: requirements/composetest/
#           target: /code
#   redis:
#     image: "redis:alpine"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - wp-site
    depends_on:
      - wordpress
    volumes:
      - www-data:/var/www/html/wordpress
    # volumes:
    #   - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb_V2/.
    container_name: mariadb
    env_file:
     - .env
    ports:
      - "5000:3306"
    networks:
      - wp-site
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    networks:
      - wp-site
    volumes:
      - www-data:/var/www/html/wordpress
    depends_on:
      - mariadb
    # volumes:
    #   - ./web:/var/www/html
    # depends_on:
    #   nginx:
    #     condition: service_started
networks:
  wp-site:
    driver: bridge
volumes:
  www-data:
    driver_opts:
      type: none
      device: /home/lbuisson/data/www-data
      o: bind
  db-data:
    driver_opts:
      type: none
      device: /home/lbuisson/data/db-data
      o: bind