# services:
#   web:
#     build: requirements/composetest/
#     ports:
#       - "8000:5000"
#     develop:
#       watch:
#         - action: sync
#           path: requirements/composetest/
#           target: /code
#   redis:
#     image: "redis:alpine"

services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
     - .env
    networks:
      - wp-site
      - adminer-db
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    # init: true
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
      - "8443:8443"
    networks:
      - wp-site
      - s-site
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - www-data:/var/www/html/

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - wp-site
    volumes:
      - www-data:/var/www/html
    depends_on:
      - mariadb
      - redis
    # healthcheck

  redis:
    container_name: redis
    build: requirements/bonus/redis/.
    networks:
      - wp-site
    restart: always

  # static-site:
  #   container_name: static-site
  #   build: requirements/bonus/static-site/.
  #   restart: always
  #   networks:
  #     - s-site

  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    restart: always
    env_file:
      - .env
    networks:
      - wp-site
    volumes:
      - www-data:/var/www/html:rw
    depends_on:
      wordpress:
        condition: service_started #healthy
    ports:
      - "21:21"

  adminer:
      build: requirements/bonus/adminer/.
      container_name: adminer
      ports:
        - 8080:8080
      depends_on:
        - mariadb 
      restart: always
      networks:
        - adminer-db

networks:
  wp-site:
    driver: bridge
  s-site:
    driver: bridge
  adminer-db:
    driver: bridge

volumes:
  www-data:
    driver_opts:
      type: local
      device: ${HOME}/data/www-data
      o: bind
  db-data:
    driver_opts:
      type: none
      device: ${HOME}/data/db-data
      o: bind